version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    container_name: dataBase
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  server:
    build: ./server/
    depends_on:
      - mysqldb
    container_name: server
    restart: unless-stopped
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - ./server:/app
      
  client:
    build: ./client/
    container_name: client_frontend
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    tty: true
volumes: 
  db: