# action.yml

name: dcoker-ci-cd
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ "bubu" ]
  pull_request:
    branches: [ "bubu" ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      MYSQLDB_USER: 'root'
      MYSQLDB_DATABASE: 'db'
      MYSQLDB_ROOT_PASSWORD: ${{secrets.MYSQLDB_ROOT_PASSWORD}}
      MYSQLDB_LOCAL_PORT: '3307'
      MYSQLDB_DOCKER_PORT: '3306'
      NODE_LOCAL_PORT: '8080'
      NODE_DOCKER_PORT: '8080'

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"