# action.yml

name: dcoker-ci-cd
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ "bubu" ]
  pull_request:
    branches: [ "bubu" ]
jobs:

  build-in-docker:
    runs-on: ubuntu-latest
    env:
      MYSQLDB_USER: 'root'
      MYSQLDB_DATABASE: 'db'
      MYSQLDB_ROOT_PASSWORD: ${{secrets.MYSQLDB_ROOT_PASSWORD}}
      MYSQLDB_LOCAL_PORT: '3307'
      MYSQLDB_DOCKER_PORT: '3306'
      NODE_LOCAL_PORT: '8080'
      NODE_DOCKER_PORT: '8080'
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"

  test-mocks-ui:
    needs: build-in-docker
    runs-on: ubuntu-latest
    steps:
      - name: add some mock tests
        run: echo '\033[32m All test on client are success \033[0m'

  test-mocks-server:
    needs: build-in-docker
    runs-on: ubuntu-latest
    steps:
      - name: add some mock tests
        run: echo '\033[32m All test on server are success \033[0m'

  test-server:
    needs: test-mocks-server
    runs-on: ubuntu-latest
    steps:
      - name: deploy on test server
        run: |
          echo '\033[32m deployment on mock server success \033[0m'
          echo 'wait confirmation'

  production:
    needs: test-server
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo '\033[32m deployment success \033[0m'